---
- include: remote.yml
  when: target == 'server'

- name: Create and migrate DB
  command: /bin/bash -l -c 'rake db:create db:migrate' chdir={{ app_path }}
  sudo_user: '{{ user_name }}'
  ignore_errors: yes
  tags:
    - rails
    - db

- name: Echo cd into .bashrc
  command: /bin/bash -l -c 'echo "cd /code-corps-api" >> /home/vagrant/.bashrc'
