Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/IndentationConsistency:
  EnforcedStyle: rails
Style/DotPosition:
  EnforcedStyle: leading
# Alignment of parameters in multi-line method calls.
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
