version: "2"

services:
  db:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  elasticsearch:
    image: elasticsearch
    expose:
      - "9200"

  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  redis:
    image: redis
    ports:
      - 6380:6379
    volumes:
      - redis-data:/var/lib/redis

  web: &api_base
    build: .
    command: foreman s -f Procfile.dev
    depends_on:
      - db
      - elasticsearch
      - redis
    environment: &api_environment
      ELASTICSEARCH_URL: http://elasticsearch:9200
      RACK_ENV: development
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      VIRTUAL_HOST: lvh.me,api.lvh.me
    links:
      - db
      - elasticsearch
    ports:
      - 5001:5000
    volumes:
      - .:/code-corps-api

  test:
    <<: *api_base
    command: guard start --no-bundler-warning --no-interactions
    environment:
      <<: *api_environment
      RACK_ENV: test
      RAILS_ENV: test
    ports: []

volumes:
  postgres-data:
  redis-data:

