test:
  adapter: postgresql
  database: code_corps_test
  host: localhost
  password: password
development:
  adapter: postgresql
  database: code_corps_dev
  role: postgres
  password: password
  host: localhost
